name: Node.js CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS using SSH
        uses: appleboy/ssh-action@v0.1.1 # Use a stable version of the SSH action
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # Navigate to the project directory on the server
            cd /var/www/html/anaa-developers/client

            # Fetch all updates from the remote repository
            git fetch --all

            # Reset the current branch to match the remote main branch
            git reset --hard origin/main

            # Ensure environment variables are set up correctly
            cp .env.example .env

            # Install necessary dependencies
            npm install --legacy-peer-deps

            # Build the project
            npm run build

            # Check if PM2 process exists, if so, restart it, otherwise start a new one
            if pm2 describe anaa-developers-client > /dev/null; then
              pm2 restart anaa-developers-client
            else
              pm2 start npm --name "anaa-developers-client" -- run start
            fi

            # Save PM2 process list to ensure process persists
            pm2 save

            # Restart PM2 if there are any issues with the current process
            pm2 restart all
