name: Node.js CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci --legacy-peer-deps
          elif [ -f pnpm-lock.yaml ]; then
            npm install -g pnpm && pnpm install --frozen-lockfile
          else
            echo "No lockfile found for dependency installation."
            exit 1
          fi

      - name: Build application
        run: npm run build

      - name: Check build output
        run: |
          if [ -d ".next" ]; then
            echo ".next directory exists"
            ls -la .next
          else
            echo ".next directory does not exist"
            exit 1
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: .next/**

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: .next

      - name: Verify downloaded artifact
        run: |
          if [ -d ".next" ]; then
            echo ".next directory exists"
            ls -la .next
          else
            echo ".next directory does not exist"
            exit 1
          fi

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # Navigate to the project directory
            cd /var/www/html/anaa-developers/client

            # Pull latest changes from the repository
            git fetch --all
            git reset --hard origin/main

            # Copy environment variables
            cp .env.example .env

            # Build the Docker image
            docker build -t anaa-developers-client .

            # Stop and remove existing containers
            docker stop anaa-developers-client || true
            docker rm anaa-developers-client || true

            # Run the new container
            docker run -d --name anaa-developers-client -p 5011:3000 anaa-developers-client

